/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponse } from '../../models/cart-response';

export interface GetCartDetails$Params {
  cartId: number;
}

export function getCartDetails(http: HttpClient, rootUrl: string, params: GetCartDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponse>> {
  const rb = new RequestBuilder(rootUrl, getCartDetails.PATH, 'get');
  if (params) {
    rb.path('cartId', params.cartId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponse>;
    })
  );
}

getCartDetails.PATH = '/api/cart/{cartId}';
