/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Users } from '../models/users';
export interface Address {
  city?: string;
  country?: string;
  id?: number;
  postalCode?: string;
  state?: string;
  street?: string;
  user?: Users;
}
