/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cart } from '../models/cart';
import { Product } from '../models/product';
export interface CartProduct {
  cart?: Cart;
  id?: number;
  product?: Product;
  quantity?: number;
}
