/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartProduct } from '../models/cart-product';
import { Users } from '../models/users';
export interface Cart {
  cartProducts?: Array<CartProduct>;
  createTime?: string;
  id?: number;
  ordered?: boolean;
  status?: 'STARTED' | 'CHECKED_OUT' | 'ABANDONED' | 'REMOVED';
  updateTime?: string;
  user?: Users;
}
