/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartProductResponse {
  image?: string;
  name?: string;
  price?: number;
  productId?: number;
  quantity?: number;
  stockQuantity?: number;
}
