/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from './product';
export interface CartResponse {
  id?: number;
  ordered?: boolean;
  product?: Product;
  status?: 'STARTED' | 'CHECKED_OUT' | 'ABANDONED' | 'REMOVED';
  userId?: number;
}
