/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartProduct } from '../models/cart-product';
export interface CartRequest {
  ordered?: boolean;
  product?: Array<CartProduct>;
  userId?: number;
}
