/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from './product';
export interface CartRequest {
  id?: number;
  ordered?: boolean;
  product?: Product;
  userId?: number;
}
