/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface CartRequest {
  id?: number;
  ordered?: boolean;
  product?: Array<Product>;
  userId?: number;
}
