/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
import { Users } from '../models/users';
export interface OrderResponse {
  approvalStatus?: 'PENDING' | 'APPROVED' | 'PREPARING' | 'DISPATCHED' | 'DELIVERED' | 'CANCELED';
  createdAt?: string;
  customers?: Users;
  lastModifiedDate?: string;
  localDateTime?: string;
  orderId?: number;
  paymentMethod?: 'MPESA' | 'BANK' | 'BITCOIN' | 'VISA';
  products?: Array<Product>;
  reference?: string;
  totalAmount?: number;
}
