/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Orders } from '../models/orders';
export interface OrderLine {
  order?: Orders;
  orderLineId?: number;
  productId?: number;
  quantity?: number;
  status?: 'PROCESSING' | 'SHIPPED' | 'DELIVERED';
}
