/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseProductRequest } from './purchase-product-request';
import { Users } from './users';
export interface OrderRequest {
  customers: Users;
  orderId?: number;
  paymentMethod: 'MPESA' | 'BANK' | 'BITCOIN' | 'VISA';
  products: Array<PurchaseProductRequest>;
  reference: string;
  totalAmount?: number;
}
