/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Users } from '../models/users';
export interface PaymentRequest {
  amount?: number;
  customer?: Users;
  orderId?: number;
  orderReference?: string;
  paymentMethod?: 'MPESA' | 'BANK' | 'BITCOIN' | 'VISA';
}
