/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface PrescriptionItem {
  id?: number;
  product?: Product;
  quantity?: number;
}
