/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Product {
  createdDate?: string;
  description?: string;
  expiryDate?: string;
  id?: number;
  image?: string;
  lastModifiedDate?: string;
  manufacturer?: string;
  name?: string;
  price?: number;
  stockQuantity?: number;
  type?: 'SYRUP' | 'TABLETS' | 'OINTMENTS';
}
