/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductCategoryRequest {
  description?: string;
  id?: number;
  image?: string;
  name?: string;
}
