/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Users } from '../models/users';
export interface Token {
  createdAt?: string;
  expiresAt?: string;
  token?: string;
  tokenId?: number;
  users?: Users;
  validatedAt?: string;
}
