/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserReport } from '../../models/user-report';

export interface GetAllCustomersReport$Params {
  startDate?: string;
  endDate?: string;
}

export function getAllCustomersReport(http: HttpClient, rootUrl: string, params?: GetAllCustomersReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserReport>>> {
  const rb = new RequestBuilder(rootUrl, getAllCustomersReport.PATH, 'get');
  if (params) {
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserReport>>;
    })
  );
}

getAllCustomersReport.PATH = '/api/customers/report';
