/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createCondition } from '../fn/health-condition-controller/create-condition';
import { CreateCondition$Params } from '../fn/health-condition-controller/create-condition';
import { getAllConditions } from '../fn/health-condition-controller/get-all-conditions';
import { GetAllConditions$Params } from '../fn/health-condition-controller/get-all-conditions';
import { HealthConditionResponse } from '../models/health-condition-response';

@Injectable({ providedIn: 'root' })
export class HealthConditionControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllConditions()` */
  static readonly GetAllConditionsPath = '/api/condition';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllConditions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllConditions$Response(params?: GetAllConditions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HealthConditionResponse>>> {
    return getAllConditions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllConditions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllConditions(params?: GetAllConditions$Params, context?: HttpContext): Observable<Array<HealthConditionResponse>> {
    return this.getAllConditions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<HealthConditionResponse>>): Array<HealthConditionResponse> => r.body)
    );
  }

  /** Path part for operation `createCondition()` */
  static readonly CreateConditionPath = '/api/condition';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCondition()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCondition$Response(params: CreateCondition$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return createCondition(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCondition$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCondition(params: CreateCondition$Params, context?: HttpContext): Observable<string> {
    return this.createCondition$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
