/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createMedicine } from '../fn/medicine-ap-is/create-medicine';
import { CreateMedicine$Params } from '../fn/medicine-ap-is/create-medicine';
import { deleteMedicine } from '../fn/medicine-ap-is/delete-medicine';
import { DeleteMedicine$Params } from '../fn/medicine-ap-is/delete-medicine';
import { getAllMedicines } from '../fn/medicine-ap-is/get-all-medicines';
import { GetAllMedicines$Params } from '../fn/medicine-ap-is/get-all-medicines';
import { getMedicineById } from '../fn/medicine-ap-is/get-medicine-by-id';
import { GetMedicineById$Params } from '../fn/medicine-ap-is/get-medicine-by-id';
import { getNewArrivals } from '../fn/medicine-ap-is/get-new-arrivals';
import { GetNewArrivals$Params } from '../fn/medicine-ap-is/get-new-arrivals';
import { getProductsByCategory } from '../fn/medicine-ap-is/get-products-by-category';
import { GetProductsByCategory$Params } from '../fn/medicine-ap-is/get-products-by-category';
import { getProductsByCondition } from '../fn/medicine-ap-is/get-products-by-condition';
import { GetProductsByCondition$Params } from '../fn/medicine-ap-is/get-products-by-condition';
import { getSpecialOffers } from '../fn/medicine-ap-is/get-special-offers';
import { GetSpecialOffers$Params } from '../fn/medicine-ap-is/get-special-offers';
import { getTrendingProducts } from '../fn/medicine-ap-is/get-trending-products';
import { GetTrendingProducts$Params } from '../fn/medicine-ap-is/get-trending-products';
import { PageResponseProductResponse } from '../models/page-response-product-response';
import { ProductResponse } from '../models/product-response';
import { PurchaseProductResponse } from '../models/purchase-product-response';
import { purchaseProducts } from '../fn/medicine-ap-is/purchase-products';
import { PurchaseProducts$Params } from '../fn/medicine-ap-is/purchase-products';
import { updateMedicine } from '../fn/medicine-ap-is/update-medicine';
import { UpdateMedicine$Params } from '../fn/medicine-ap-is/update-medicine';

@Injectable({ providedIn: 'root' })
export class MedicineApIsService extends BaseService {
  constructor() {
    const config = inject(ApiConfiguration);
    const http = inject(HttpClient);

    super(config, http);
  }

  /** Path part for operation `getAllMedicines()` */
  static readonly GetAllMedicinesPath = '/api/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllMedicines()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllMedicines$Response(params?: GetAllMedicines$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseProductResponse>> {
    return getAllMedicines(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllMedicines$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllMedicines(params?: GetAllMedicines$Params, context?: HttpContext): Observable<PageResponseProductResponse> {
    return this.getAllMedicines$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseProductResponse>): PageResponseProductResponse => r.body)
    );
  }

  /** Path part for operation `updateMedicine()` */
  static readonly UpdateMedicinePath = '/api/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMedicine()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMedicine$Response(params: UpdateMedicine$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateMedicine(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMedicine$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMedicine(params: UpdateMedicine$Params, context?: HttpContext): Observable<void> {
    return this.updateMedicine$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createMedicine()` */
  static readonly CreateMedicinePath = '/api/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createMedicine()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMedicine$Response(params?: CreateMedicine$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return createMedicine(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createMedicine$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMedicine(params?: CreateMedicine$Params, context?: HttpContext): Observable<string> {
    return this.createMedicine$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `purchaseProducts()` */
  static readonly PurchaseProductsPath = '/api/products/purchase';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `purchaseProducts()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purchaseProducts$Response(params: PurchaseProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PurchaseProductResponse>>> {
    return purchaseProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `purchaseProducts$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purchaseProducts(params: PurchaseProducts$Params, context?: HttpContext): Observable<Array<PurchaseProductResponse>> {
    return this.purchaseProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PurchaseProductResponse>>): Array<PurchaseProductResponse> => r.body)
    );
  }

  /** Path part for operation `getMedicineById()` */
  static readonly GetMedicineByIdPath = '/api/products/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMedicineById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMedicineById$Response(params: GetMedicineById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return getMedicineById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMedicineById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMedicineById(params: GetMedicineById$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.getMedicineById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `deleteMedicine()` */
  static readonly DeleteMedicinePath = '/api/products/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteMedicine()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMedicine$Response(params: DeleteMedicine$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteMedicine(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteMedicine$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMedicine(params: DeleteMedicine$Params, context?: HttpContext): Observable<void> {
    return this.deleteMedicine$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getTrendingProducts()` */
  static readonly GetTrendingProductsPath = '/api/products/trending';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTrendingProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTrendingProducts$Response(params?: GetTrendingProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return getTrendingProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTrendingProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTrendingProducts(params?: GetTrendingProducts$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.getTrendingProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /** Path part for operation `getSpecialOffers()` */
  static readonly GetSpecialOffersPath = '/api/products/offers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSpecialOffers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecialOffers$Response(params?: GetSpecialOffers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return getSpecialOffers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSpecialOffers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecialOffers(params?: GetSpecialOffers$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.getSpecialOffers$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /** Path part for operation `getNewArrivals()` */
  static readonly GetNewArrivalsPath = '/api/products/new-arrivals';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getNewArrivals()` instead.
   *
   * This method doesn't expect any request body.
   */
  getNewArrivals$Response(params?: GetNewArrivals$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return getNewArrivals(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getNewArrivals$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getNewArrivals(params?: GetNewArrivals$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.getNewArrivals$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /** Path part for operation `getProductsByCondition()` */
  static readonly GetProductsByConditionPath = '/api/products/condition/{conditionId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductsByCondition()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductsByCondition$Response(params: GetProductsByCondition$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return getProductsByCondition(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductsByCondition$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductsByCondition(params: GetProductsByCondition$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.getProductsByCondition$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /** Path part for operation `getProductsByCategory()` */
  static readonly GetProductsByCategoryPath = '/api/products/category/{categoryId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductsByCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductsByCategory$Response(params: GetProductsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return getProductsByCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductsByCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductsByCategory(params: GetProductsByCategory$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.getProductsByCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

}
