/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { approvePrescription } from '../fn/prescription-controller/approve-prescription';
import { ApprovePrescription$Params } from '../fn/prescription-controller/approve-prescription';
import { getAllPrescriptions } from '../fn/prescription-controller/get-all-prescriptions';
import { GetAllPrescriptions$Params } from '../fn/prescription-controller/get-all-prescriptions';
import { getLatestApprovedPrescription } from '../fn/prescription-controller/get-latest-approved-prescription';
import { GetLatestApprovedPrescription$Params } from '../fn/prescription-controller/get-latest-approved-prescription';
import { getUserPrescriptions } from '../fn/prescription-controller/get-user-prescriptions';
import { GetUserPrescriptions$Params } from '../fn/prescription-controller/get-user-prescriptions';
import { PrescriptionResponse } from '../models/prescription-response';
import { uploadPrescription } from '../fn/prescription-controller/upload-prescription';
import { UploadPrescription$Params } from '../fn/prescription-controller/upload-prescription';

@Injectable({ providedIn: 'root' })
export class PrescriptionControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `approvePrescription()` */
  static readonly ApprovePrescriptionPath = '/api/prescriptions/{id}/approve';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approvePrescription()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  approvePrescription$Response(params: ApprovePrescription$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return approvePrescription(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approvePrescription$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  approvePrescription(params: ApprovePrescription$Params, context?: HttpContext): Observable<{
}> {
    return this.approvePrescription$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getAllPrescriptions()` */
  static readonly GetAllPrescriptionsPath = '/api/prescriptions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPrescriptions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPrescriptions$Response(params?: GetAllPrescriptions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PrescriptionResponse>>> {
    return getAllPrescriptions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPrescriptions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPrescriptions(params?: GetAllPrescriptions$Params, context?: HttpContext): Observable<Array<PrescriptionResponse>> {
    return this.getAllPrescriptions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PrescriptionResponse>>): Array<PrescriptionResponse> => r.body)
    );
  }

  /** Path part for operation `uploadPrescription()` */
  static readonly UploadPrescriptionPath = '/api/prescriptions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadPrescription()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadPrescription$Response(params?: UploadPrescription$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return uploadPrescription(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadPrescription$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadPrescription(params?: UploadPrescription$Params, context?: HttpContext): Observable<void> {
    return this.uploadPrescription$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getUserPrescriptions()` */
  static readonly GetUserPrescriptionsPath = '/api/prescriptions/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserPrescriptions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserPrescriptions$Response(params?: GetUserPrescriptions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PrescriptionResponse>>> {
    return getUserPrescriptions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserPrescriptions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserPrescriptions(params?: GetUserPrescriptions$Params, context?: HttpContext): Observable<Array<PrescriptionResponse>> {
    return this.getUserPrescriptions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PrescriptionResponse>>): Array<PrescriptionResponse> => r.body)
    );
  }

  /** Path part for operation `getLatestApprovedPrescription()` */
  static readonly GetLatestApprovedPrescriptionPath = '/api/prescriptions/user/latest-approved';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLatestApprovedPrescription()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLatestApprovedPrescription$Response(params?: GetLatestApprovedPrescription$Params, context?: HttpContext): Observable<StrictHttpResponse<PrescriptionResponse>> {
    return getLatestApprovedPrescription(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLatestApprovedPrescription$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLatestApprovedPrescription(params?: GetLatestApprovedPrescription$Params, context?: HttpContext): Observable<PrescriptionResponse> {
    return this.getLatestApprovedPrescription$Response(params, context).pipe(
      map((r: StrictHttpResponse<PrescriptionResponse>): PrescriptionResponse => r.body)
    );
  }

}
