/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProductCategory } from '../fn/product-category-controller/create-product-category';
import { CreateProductCategory$Params } from '../fn/product-category-controller/create-product-category';
import { getProductCategory } from '../fn/product-category-controller/get-product-category';
import { GetProductCategory$Params } from '../fn/product-category-controller/get-product-category';
import { getProductCategoryById } from '../fn/product-category-controller/get-product-category-by-id';
import { GetProductCategoryById$Params } from '../fn/product-category-controller/get-product-category-by-id';
import { ProductCategoryResponse } from '../models/product-category-response';

@Injectable({ providedIn: 'root' })
export class ProductCategoryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getProductCategory()` */
  static readonly GetProductCategoryPath = '/api/product-category';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductCategory$Response(params?: GetProductCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductCategoryResponse>>> {
    return getProductCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductCategory(params?: GetProductCategory$Params, context?: HttpContext): Observable<Array<ProductCategoryResponse>> {
    return this.getProductCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductCategoryResponse>>): Array<ProductCategoryResponse> => r.body)
    );
  }

  /** Path part for operation `createProductCategory()` */
  static readonly CreateProductCategoryPath = '/api/product-category';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProductCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProductCategory$Response(params?: CreateProductCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return createProductCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProductCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProductCategory(params?: CreateProductCategory$Params, context?: HttpContext): Observable<string> {
    return this.createProductCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getProductCategoryById()` */
  static readonly GetProductCategoryByIdPath = '/api/product-category/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductCategoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductCategoryById$Response(params: GetProductCategoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductCategoryResponse>> {
    return getProductCategoryById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductCategoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductCategoryById(params: GetProductCategoryById$Params, context?: HttpContext): Observable<ProductCategoryResponse> {
    return this.getProductCategoryById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductCategoryResponse>): ProductCategoryResponse => r.body)
    );
  }

}
