/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getShipmentById } from '../fn/shipment-tracking-ap-is/get-shipment-by-id';
import { GetShipmentById$Params } from '../fn/shipment-tracking-ap-is/get-shipment-by-id';
import { getShipments } from '../fn/shipment-tracking-ap-is/get-shipments';
import { GetShipments$Params } from '../fn/shipment-tracking-ap-is/get-shipments';
import { notifyTracking } from '../fn/shipment-tracking-ap-is/notify-tracking';
import { NotifyTracking$Params } from '../fn/shipment-tracking-ap-is/notify-tracking';
import { ShipmentResponse } from '../models/shipment-response';

@Injectable({ providedIn: 'root' })
export class ShipmentTrackingApIsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notifyTracking()` */
  static readonly NotifyTrackingPath = '/api/shipments/{shipmentId}/notify-tracking';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notifyTracking()` instead.
   *
   * This method doesn't expect any request body.
   */
  notifyTracking$Response(params: NotifyTracking$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notifyTracking(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notifyTracking$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notifyTracking(params: NotifyTracking$Params, context?: HttpContext): Observable<void> {
    return this.notifyTracking$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getShipments()` */
  static readonly GetShipmentsPath = '/api/shipments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getShipments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShipments$Response(params?: GetShipments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipmentResponse>>> {
    return getShipments(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getShipments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShipments(params?: GetShipments$Params, context?: HttpContext): Observable<Array<ShipmentResponse>> {
    return this.getShipments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ShipmentResponse>>): Array<ShipmentResponse> => r.body)
    );
  }

  /** Path part for operation `getShipmentById()` */
  static readonly GetShipmentByIdPath = '/api/shipments/{shipmentId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getShipmentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShipmentById$Response(params: GetShipmentById$Params, context?: HttpContext): Observable<StrictHttpResponse<ShipmentResponse>> {
    return getShipmentById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getShipmentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getShipmentById(params: GetShipmentById$Params, context?: HttpContext): Observable<ShipmentResponse> {
    return this.getShipmentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShipmentResponse>): ShipmentResponse => r.body)
    );
  }

}
