/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartRequest {
  id?: number;
  ordered?: boolean;
  productId?: number;
  stockQuantity?: number;
  userId?: number;
}
