/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseProductRequest } from '../models/purchase-product-request';
export interface OrderRequest {
  customerId: number;
  orderId?: number;
  paymentMethod: 'MPESA' | 'BANK' | 'BITCOIN' | 'VISA';
  products: Array<PurchaseProductRequest>;
  reference: string;
  totalAmount?: number;
}
