/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderResponse {
  customerId?: number;
  orderId?: number;
  paymentMethod?: 'MPESA' | 'BANK' | 'BITCOIN' | 'VISA';
  reference?: string;
  totalAmount?: number;
}
