/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  customerId?: number;
  dateOfBirth?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  location?: string;
  password?: string;
  phone?: string;
}
