/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RevenueReportResponse } from '../../models/revenue-report-response';

export interface GetRevenueReport$Params {
  period?: string;
}

export function getRevenueReport(http: HttpClient, rootUrl: string, params?: GetRevenueReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RevenueReportResponse>>> {
  const rb = new RequestBuilder(rootUrl, getRevenueReport.PATH, 'get');
  if (params) {
    rb.query('period', params.period, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RevenueReportResponse>>;
    })
  );
}

getRevenueReport.PATH = '/api/orders/reports/revenue';
