/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderAdminUpdateRequest } from '../../models/order-admin-update-request';
import { ShipmentResponse } from '../../models/shipment-response';

export interface UpdateAdminWorkflow$Params {
  orderId: number;
      body: OrderAdminUpdateRequest
}

export function updateAdminWorkflow(http: HttpClient, rootUrl: string, params: UpdateAdminWorkflow$Params, context?: HttpContext): Observable<StrictHttpResponse<ShipmentResponse>> {
  const rb = new RequestBuilder(rootUrl, updateAdminWorkflow.PATH, 'patch');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShipmentResponse>;
    })
  );
}

updateAdminWorkflow.PATH = '/api/orders/{orderId}/admin-workflow';
