/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addCart } from '../fn/cart-controller/add-cart';
import { AddCart$Params } from '../fn/cart-controller/add-cart';
import { CartResponse } from '../models/cart-response';
import { getCartsByStatus } from '../fn/cart-controller/get-carts-by-status';
import { GetCartsByStatus$Params } from '../fn/cart-controller/get-carts-by-status';
import { getUserCart } from '../fn/cart-controller/get-user-cart';
import { GetUserCart$Params } from '../fn/cart-controller/get-user-cart';
import { placeOrder } from '../fn/cart-controller/place-order';
import { PlaceOrder$Params } from '../fn/cart-controller/place-order';
import { removeFromCart } from '../fn/cart-controller/remove-from-cart';
import { RemoveFromCart$Params } from '../fn/cart-controller/remove-from-cart';

@Injectable({ providedIn: 'root' })
export class CartControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addCart()` */
  static readonly AddCartPath = '/api/cart';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addCart()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCart$Response(params: AddCart$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponse>> {
    return addCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addCart$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCart(params: AddCart$Params, context?: HttpContext): Observable<CartResponse> {
    return this.addCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<CartResponse>): CartResponse => r.body)
    );
  }

  /** Path part for operation `placeOrder()` */
  static readonly PlaceOrderPath = '/api/cart/checkout/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `placeOrder()` instead.
   *
   * This method doesn't expect any request body.
   */
  placeOrder$Response(params: PlaceOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return placeOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `placeOrder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  placeOrder(params: PlaceOrder$Params, context?: HttpContext): Observable<void> {
    return this.placeOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getCartsByStatus()` */
  static readonly GetCartsByStatusPath = '/api/cart/status/{status}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCartsByStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCartsByStatus$Response(params: GetCartsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartResponse>>> {
    return getCartsByStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCartsByStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCartsByStatus(params: GetCartsByStatus$Params, context?: HttpContext): Observable<Array<CartResponse>> {
    return this.getCartsByStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CartResponse>>): Array<CartResponse> => r.body)
    );
  }

  /** Path part for operation `getUserCart()` */
  static readonly GetUserCartPath = '/api/cart/add/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserCart$Response(params: GetUserCart$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartResponse>>> {
    return getUserCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserCart(params: GetUserCart$Params, context?: HttpContext): Observable<Array<CartResponse>> {
    return this.getUserCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CartResponse>>): Array<CartResponse> => r.body)
    );
  }

  /** Path part for operation `removeFromCart()` */
  static readonly RemoveFromCartPath = '/api/cart/{cartId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeFromCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeFromCart$Response(params: RemoveFromCart$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return removeFromCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeFromCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeFromCart(params: RemoveFromCart$Params, context?: HttpContext): Observable<void> {
    return this.removeFromCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
