/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addCustomer } from '../fn/customer-controller/add-customer';
import { AddCustomer$Params } from '../fn/customer-controller/add-customer';
import { CustomerResponse } from '../models/customer-response';
import { deleteCustomer } from '../fn/customer-controller/delete-customer';
import { DeleteCustomer$Params } from '../fn/customer-controller/delete-customer';
import { getAllCustomers } from '../fn/customer-controller/get-all-customers';
import { GetAllCustomers$Params } from '../fn/customer-controller/get-all-customers';
import { getCustomer } from '../fn/customer-controller/get-customer';
import { GetCustomer$Params } from '../fn/customer-controller/get-customer';
import { updateCustomer } from '../fn/customer-controller/update-customer';
import { UpdateCustomer$Params } from '../fn/customer-controller/update-customer';

@Injectable({ providedIn: 'root' })
export class CustomerControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllCustomers()` */
  static readonly GetAllCustomersPath = '/customers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCustomers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCustomers$Response(params?: GetAllCustomers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerResponse>>> {
    return getAllCustomers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCustomers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCustomers(params?: GetAllCustomers$Params, context?: HttpContext): Observable<Array<CustomerResponse>> {
    return this.getAllCustomers$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CustomerResponse>>): Array<CustomerResponse> => r.body)
    );
  }

  /** Path part for operation `updateCustomer()` */
  static readonly UpdateCustomerPath = '/customers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCustomer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCustomer$Response(params: UpdateCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCustomer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCustomer(params: UpdateCustomer$Params, context?: HttpContext): Observable<void> {
    return this.updateCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `addCustomer()` */
  static readonly AddCustomerPath = '/customers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addCustomer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCustomer$Response(params: AddCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return addCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addCustomer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCustomer(params: AddCustomer$Params, context?: HttpContext): Observable<string> {
    return this.addCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getCustomer()` */
  static readonly GetCustomerPath = '/customers/{customerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCustomer()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCustomer$Response(params: GetCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerResponse>> {
    return getCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCustomer$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCustomer(params: GetCustomer$Params, context?: HttpContext): Observable<CustomerResponse> {
    return this.getCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomerResponse>): CustomerResponse => r.body)
    );
  }

  /** Path part for operation `deleteCustomer()` */
  static readonly DeleteCustomerPath = '/customers/{customerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCustomer()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCustomer$Response(params: DeleteCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCustomer$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCustomer(params: DeleteCustomer$Params, context?: HttpContext): Observable<void> {
    return this.deleteCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
