/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findOrderById } from '../fn/order-line-controller/find-order-by-id';
import { FindOrderById$Params } from '../fn/order-line-controller/find-order-by-id';
import { OrderLineResponse } from '../models/order-line-response';

@Injectable({ providedIn: 'root' })
export class OrderLineControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findOrderById()` */
  static readonly FindOrderByIdPath = '/api/orderline/order/{orderId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findOrderById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findOrderById$Response(params: FindOrderById$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderLineResponse>>> {
    return findOrderById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findOrderById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findOrderById(params: FindOrderById$Params, context?: HttpContext): Observable<Array<OrderLineResponse>> {
    return this.findOrderById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OrderLineResponse>>): Array<OrderLineResponse> => r.body)
    );
  }

}
