/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductCategoryResponse } from '../../models/product-category-response';

export interface GetProductCategory$Params {
}

export function getProductCategory(http: HttpClient, rootUrl: string, params?: GetProductCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductCategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getProductCategory.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductCategoryResponse>>;
    })
  );
}

getProductCategory.PATH = '/api/product-category';
