/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MedicineResponse } from '../../models/medicine-response';

export interface GetMedicineById$Params {
  medicineId: number;
}

export function getMedicineById(http: HttpClient, rootUrl: string, params: GetMedicineById$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicineResponse>> {
  const rb = new RequestBuilder(rootUrl, getMedicineById.PATH, 'get');
  if (params) {
    rb.path('medicineId', params.medicineId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MedicineResponse>;
    })
  );
}

getMedicineById.PATH = '/api/medicines/{medicineId}';
