/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchaseProductResponse {
  description?: string;
  image?: string;
  name?: string;
  price?: number;
  productId?: number;
  quantity?: number;
}
