/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Roles {
  createdDate?: string;
  lastModifiedDate?: string;
  name?: string;
  roleId?: number;
}
