/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerReportResponse } from '../../models/customer-report-response';

export interface GetCustomerReport$Params {
  period?: string;
}

export function getCustomerReport(http: HttpClient, rootUrl: string, params?: GetCustomerReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerReportResponse>>> {
  const rb = new RequestBuilder(rootUrl, getCustomerReport.PATH, 'get');
  if (params) {
    rb.query('period', params.period, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CustomerReportResponse>>;
    })
  );
}

getCustomerReport.PATH = '/api/customers/reports';
