/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { MedicineApIsService } from './services/medicine-ap-is.service';
import { PrescriptionControllerService } from './services/prescription-controller.service';
import { CustomersApIsService } from './services/customers-ap-is.service';
import { AuthenticationApIsService } from './services/authentication-ap-is.service';
import { PaymentControllerService } from './services/payment-controller.service';
import { OrderApIsService } from './services/order-ap-is.service';
import { CartControllerService } from './services/cart-controller.service';
import { OrderLineControllerService } from './services/order-line-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    MedicineApIsService,
    PrescriptionControllerService,
    CustomersApIsService,
    AuthenticationApIsService,
    PaymentControllerService,
    OrderApIsService,
    CartControllerService,
    OrderLineControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
