/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { CustomerRequest } from './models/customer-request';
export type { CustomerResponse } from './models/customer-response';
export type { MedicineRequest } from './models/medicine-request';
export type { MedicineResponse } from './models/medicine-response';
export type { PageResponseMedicineResponse } from './models/page-response-medicine-response';
export type { RegistrationRequest } from './models/registration-request';
