/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthConditionResponse } from '../../models/health-condition-response';

export interface GetAllConditions$Params {
}

export function getAllConditions(http: HttpClient, rootUrl: string, params?: GetAllConditions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HealthConditionResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllConditions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HealthConditionResponse>>;
    })
  );
}

getAllConditions.PATH = '/api/condition';
