/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShipmentResponse } from '../../models/shipment-response';

export interface GetShipments$Params {
  search?: string;
  statuses?: Array<'IN_PROGRESS' | 'ARRIVED' | 'CANCELED' | 'DRAFT' | 'DELAYED'>;
  tab?: string;
}

export function getShipments(http: HttpClient, rootUrl: string, params?: GetShipments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipmentResponse>>> {
  const rb = new RequestBuilder(rootUrl, getShipments.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('statuses', params.statuses, {});
    rb.query('tab', params.tab, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShipmentResponse>>;
    })
  );
}

getShipments.PATH = '/api/shipments';
