/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShipmentResponse } from '../../models/shipment-response';

export interface GetShipmentById$Params {
  shipmentId: string;
}

export function getShipmentById(http: HttpClient, rootUrl: string, params: GetShipmentById$Params, context?: HttpContext): Observable<StrictHttpResponse<ShipmentResponse>> {
  const rb = new RequestBuilder(rootUrl, getShipmentById.PATH, 'get');
  if (params) {
    rb.path('shipmentId', params.shipmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShipmentResponse>;
    })
  );
}

getShipmentById.PATH = '/api/shipments/{shipmentId}';
