/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrescriptionResponse } from '../../models/prescription-response';

export interface GetLatestApprovedPrescription$Params {
}

export function getLatestApprovedPrescription(http: HttpClient, rootUrl: string, params?: GetLatestApprovedPrescription$Params, context?: HttpContext): Observable<StrictHttpResponse<PrescriptionResponse>> {
  const rb = new RequestBuilder(rootUrl, getLatestApprovedPrescription.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PrescriptionResponse>;
    })
  );
}

getLatestApprovedPrescription.PATH = '/api/prescriptions/user/latest-approved';
