/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrescriptionItemRequest } from '../../models/prescription-item-request';

export interface ReviewPrescription$Params {
  id: number;
  approved: boolean;
      body?: Array<PrescriptionItemRequest>
}

export function reviewPrescription(http: HttpClient, rootUrl: string, params: ReviewPrescription$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, reviewPrescription.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('approved', params.approved, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

reviewPrescription.PATH = '/api/prescriptions/{id}/review';
