name: Pharmacy Deployment
on:
    push:
        branches:
            - "main"
jobs:
    compile:
        runs-on: ubuntu-latest
        name: Compile Project
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Setup JDK
            uses: actions/setup-jdk@v4
            with:
                java-version: 21

          - name: Compile
            run: |
                cd api
                ./mvnw clean compile
