name: Pharmacy Deployment
on:
    push:
        branches:
            - "main"
jobs:
    compile-and-test:
        runs-on: ubuntu-latest
        name: Compile and Test Project
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Setup JDK
            uses: actions/setup-java@v4
            with:
                java-version: 21
                distribution: 'corretto'

          - name: Compile
            run: |
                cd api
                ./mvnw clean compile

          - name: Cache Maven Dependencies
            uses: actions/cache@v4
            with:
                path: ~/.m2
                key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml')}}
                restore-keys: ${{runner.os}}-m2

          - name: Running Unit Test
            run: |
                cd api
                ./mvnw clean test
    build-and-deploy:
        runs-on: ubuntu-latest
        name: Build & Deploy
        needs: compile-and-test
        steps:
          - name: Setup JDK
            uses: actions/setup-java@v4
            with:
                java-version: 21
                distribution: 'corretto'

          - name: Cache Maven Dependencies
            uses: actions/cache@v4
            with:
                path: ~/.m2
                key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml')}}
                restore-keys: ${{runner.os}}-m2

          - name: Build Project
            run: ./mvnw clean package DskipTests

          - name: Set up Docker
            uses: docker/setup-buildx-action@v3